# Site settings
title: NS
subtitle: "Naren Salem"
email: naren.salem@gmail.com
description: "I love to code, lead and mentor."
baseurl: ""
url: "http://narensalem.info"
twitter_username: "NarenOfTheUS"
github_username:  "naren8642"
instagram_username: "narensale"

# Build settings
markdown: kramdown
permalink: pretty

# Pagination
paginate: 5

# Sass
sass:
    style: :compressed

gems: [jekyll-paginate]

